

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    console:
      enabled: true
  cache:
    cache-names: http
    caffeine:
      spec: maximumSize=500, expireAfterAccess=30m

management.endpoints:
    web.exposure.include: info, health, metrics, scheduledtasks, sessions
    caches.enabled: true
    metrics.enabled: true
    scheduledtasks.enabled: true
    sessions.enabled: true

logging:
  level:
    org.springframework.cache: DEBUG

app:
  site-initial:
  scheduler:
    delay: 10000
    initial-delay: 5000

